---
- name: Install Wget package
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Ensure Wget is installed
      yum:
        name:
          - wget={{ deployment_version }}
        state: present
